require 'rubygems'
require 'mechanize'
require 'json'
require 'json/add/core'

require_relative 'cricos_scrape/json_struct'
require_relative 'cricos_scrape/address'
require_relative 'cricos_scrape/institution'
require_relative 'cricos_scrape/location'
require_relative 'cricos_scrape/institution_importer'
