require 'rubygems'
require 'json'
require 'json/add/core'
require 'cricos_scrape/json_struct'
require 'cricos_scrape/bulk_import_institutions'
require 'cricos_scrape/bulk_import_courses'
require 'cricos_scrape/import_contacts'
